services:
  - type: web
    name: ethara-ai-backend
    runtime: python
    rootDir: backend-python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        value: hrms-lite
      - key: PORT
        value: 10000
